(ns dram_design.actor
  "dram_design clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). DRAM cell / array design (DDR5 / LPDDR).

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; DramDevice
   {:db/ident :dram_design.DramDevice/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.DramDevice/partNumber :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.DramDevice/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.DramDevice/densityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.DramDevice/dataRateMtps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.DramDevice/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.DramDevice/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; CellArray
   {:db/ident :dram_design.CellArray/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.CellArray/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.CellArray/rows :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.CellArray/columns :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.CellArray/capacitorType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.CellArray/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.CellArray/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Bank
   {:db/ident :dram_design.Bank/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.Bank/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.Bank/bankGroup :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.Bank/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.Bank/pageSizeKb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.Bank/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.Bank/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TimingProfile
   {:db/ident :dram_design.TimingProfile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.TimingProfile/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.TimingProfile/casLatency :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.TimingProfile/tRCD :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.TimingProfile/tRP :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.TimingProfile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.TimingProfile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SpeedBin
   {:db/ident :dram_design.SpeedBin/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.SpeedBin/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.SpeedBin/grade :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.SpeedBin/voltage :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.SpeedBin/dataRateMtps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.SpeedBin/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.SpeedBin/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; JedecSpec
   {:db/ident :dram_design.JedecSpec/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dram_design.JedecSpec/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.JedecSpec/standard :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.JedecSpec/revision :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.JedecSpec/compliant :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.JedecSpec/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dram_design.JedecSpec/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"DramDevice" "CellArray" "Bank" "TimingProfile" "SpeedBin" "JedecSpec"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "dram_design: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "dram_design: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "dram_design: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── DramDevice ────────────────────────────────────────────────────────────────
(defn create-dram-device
  "Create a DramDevice."
  [port data]
  (require-fields data ["partNumber" "generation"])
  (let [id (new-id "dram_dra")
        e {:db/id id
           :dram_design.DramDevice/id id
           :dram_design.DramDevice/partNumber (get data :partNumber)
           :dram_design.DramDevice/generation (get data :generation)
           :dram_design.DramDevice/densityGb (as-long (get data :densityGb))
           :dram_design.DramDevice/dataRateMtps (as-long (get data :dataRateMtps))
           :dram_design.DramDevice/createdAt (now)
           :dram_design.DramDevice/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-dram-devices
  "List DramDevice with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-dram-devices port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.DramDevice/id))
         rows (apply-filters rows (:filter opts) [:dram_design.DramDevice/partNumber :dram_design.DramDevice/generation :dram_design.DramDevice/densityGb :dram_design.DramDevice/dataRateMtps])]
     (paginate rows opts))))

(defn get-dram-device
  "Retrieve a DramDevice by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-dram-device port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-dram-device
  "Update a DramDevice; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :partNumber) (conj [:db/add id :dram_design.DramDevice/partNumber (get data :partNumber)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :dram_design.DramDevice/generation (get data :generation)]))
                   (cond-> (contains? data :densityGb) (conj [:db/add id :dram_design.DramDevice/densityGb (as-long (get data :densityGb))]))
                   (cond-> (contains? data :dataRateMtps) (conj [:db/add id :dram_design.DramDevice/dataRateMtps (as-long (get data :dataRateMtps))]))
                   (conj [:db/add id :dram_design.DramDevice/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-dram-device
  "Delete a DramDevice."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── CellArray ────────────────────────────────────────────────────────────────
(defn create-cell-array
  "Create a CellArray."
  [port data]
  (require-fields data ["rows" "columns"])
  (let [id (new-id "dram_cel")
        e {:db/id id
           :dram_design.CellArray/id id
           :dram_design.CellArray/deviceId (get data :deviceId)
           :dram_design.CellArray/rows (as-long (get data :rows))
           :dram_design.CellArray/columns (as-long (get data :columns))
           :dram_design.CellArray/capacitorType (get data :capacitorType)
           :dram_design.CellArray/createdAt (now)
           :dram_design.CellArray/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cell-arrays
  "List CellArray with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cell-arrays port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.CellArray/id))
         rows (apply-filters rows (:filter opts) [:dram_design.CellArray/deviceId :dram_design.CellArray/rows :dram_design.CellArray/columns :dram_design.CellArray/capacitorType])]
     (paginate rows opts))))

(defn get-cell-array
  "Retrieve a CellArray by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cell-array port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cell-array
  "Update a CellArray; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :dram_design.CellArray/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :rows) (conj [:db/add id :dram_design.CellArray/rows (as-long (get data :rows))]))
                   (cond-> (contains? data :columns) (conj [:db/add id :dram_design.CellArray/columns (as-long (get data :columns))]))
                   (cond-> (contains? data :capacitorType) (conj [:db/add id :dram_design.CellArray/capacitorType (get data :capacitorType)]))
                   (conj [:db/add id :dram_design.CellArray/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cell-array
  "Delete a CellArray."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Bank ────────────────────────────────────────────────────────────────
(defn create-bank
  "Create a Bank."
  [port data]
  (require-fields data ["bankGroup" "index"])
  (let [id (new-id "dram_ban")
        e {:db/id id
           :dram_design.Bank/id id
           :dram_design.Bank/deviceId (get data :deviceId)
           :dram_design.Bank/bankGroup (as-long (get data :bankGroup))
           :dram_design.Bank/index (as-long (get data :index))
           :dram_design.Bank/pageSizeKb (as-double (get data :pageSizeKb))
           :dram_design.Bank/createdAt (now)
           :dram_design.Bank/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-banks
  "List Bank with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-banks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.Bank/id))
         rows (apply-filters rows (:filter opts) [:dram_design.Bank/deviceId :dram_design.Bank/bankGroup :dram_design.Bank/index :dram_design.Bank/pageSizeKb])]
     (paginate rows opts))))

(defn get-bank
  "Retrieve a Bank by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-bank port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-bank
  "Update a Bank; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :dram_design.Bank/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :bankGroup) (conj [:db/add id :dram_design.Bank/bankGroup (as-long (get data :bankGroup))]))
                   (cond-> (contains? data :index) (conj [:db/add id :dram_design.Bank/index (as-long (get data :index))]))
                   (cond-> (contains? data :pageSizeKb) (conj [:db/add id :dram_design.Bank/pageSizeKb (as-double (get data :pageSizeKb))]))
                   (conj [:db/add id :dram_design.Bank/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-bank
  "Delete a Bank."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TimingProfile ────────────────────────────────────────────────────────────────
(defn create-timing-profile
  "Create a TimingProfile."
  [port data]
  (require-fields data ["casLatency" "tRCD"])
  (let [id (new-id "dram_tim")
        e {:db/id id
           :dram_design.TimingProfile/id id
           :dram_design.TimingProfile/deviceId (get data :deviceId)
           :dram_design.TimingProfile/casLatency (as-long (get data :casLatency))
           :dram_design.TimingProfile/tRCD (as-long (get data :tRCD))
           :dram_design.TimingProfile/tRP (as-long (get data :tRP))
           :dram_design.TimingProfile/createdAt (now)
           :dram_design.TimingProfile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-timing-profiles
  "List TimingProfile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-timing-profiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.TimingProfile/id))
         rows (apply-filters rows (:filter opts) [:dram_design.TimingProfile/deviceId :dram_design.TimingProfile/casLatency :dram_design.TimingProfile/tRCD :dram_design.TimingProfile/tRP])]
     (paginate rows opts))))

(defn get-timing-profile
  "Retrieve a TimingProfile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-timing-profile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-timing-profile
  "Update a TimingProfile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :dram_design.TimingProfile/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :casLatency) (conj [:db/add id :dram_design.TimingProfile/casLatency (as-long (get data :casLatency))]))
                   (cond-> (contains? data :tRCD) (conj [:db/add id :dram_design.TimingProfile/tRCD (as-long (get data :tRCD))]))
                   (cond-> (contains? data :tRP) (conj [:db/add id :dram_design.TimingProfile/tRP (as-long (get data :tRP))]))
                   (conj [:db/add id :dram_design.TimingProfile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-timing-profile
  "Delete a TimingProfile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SpeedBin ────────────────────────────────────────────────────────────────
(defn create-speed-bin
  "Create a SpeedBin."
  [port data]
  (require-fields data ["grade" "voltage"])
  (let [id (new-id "dram_spe")
        e {:db/id id
           :dram_design.SpeedBin/id id
           :dram_design.SpeedBin/deviceId (get data :deviceId)
           :dram_design.SpeedBin/grade (get data :grade)
           :dram_design.SpeedBin/voltage (as-double (get data :voltage))
           :dram_design.SpeedBin/dataRateMtps (as-long (get data :dataRateMtps))
           :dram_design.SpeedBin/createdAt (now)
           :dram_design.SpeedBin/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-speed-bins
  "List SpeedBin with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-speed-bins port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.SpeedBin/id))
         rows (apply-filters rows (:filter opts) [:dram_design.SpeedBin/deviceId :dram_design.SpeedBin/grade :dram_design.SpeedBin/voltage :dram_design.SpeedBin/dataRateMtps])]
     (paginate rows opts))))

(defn get-speed-bin
  "Retrieve a SpeedBin by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-speed-bin port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-speed-bin
  "Update a SpeedBin; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :dram_design.SpeedBin/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :grade) (conj [:db/add id :dram_design.SpeedBin/grade (get data :grade)]))
                   (cond-> (contains? data :voltage) (conj [:db/add id :dram_design.SpeedBin/voltage (as-double (get data :voltage))]))
                   (cond-> (contains? data :dataRateMtps) (conj [:db/add id :dram_design.SpeedBin/dataRateMtps (as-long (get data :dataRateMtps))]))
                   (conj [:db/add id :dram_design.SpeedBin/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-speed-bin
  "Delete a SpeedBin."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── JedecSpec ────────────────────────────────────────────────────────────────
(defn create-jedec-spec
  "Create a JedecSpec."
  [port data]
  (require-fields data ["standard" "revision"])
  (let [id (new-id "dram_jed")
        e {:db/id id
           :dram_design.JedecSpec/id id
           :dram_design.JedecSpec/deviceId (get data :deviceId)
           :dram_design.JedecSpec/standard (get data :standard)
           :dram_design.JedecSpec/revision (get data :revision)
           :dram_design.JedecSpec/compliant (as-bool (get data :compliant))
           :dram_design.JedecSpec/createdAt (now)
           :dram_design.JedecSpec/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-jedec-specs
  "List JedecSpec with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-jedec-specs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dram_design.JedecSpec/id))
         rows (apply-filters rows (:filter opts) [:dram_design.JedecSpec/deviceId :dram_design.JedecSpec/standard :dram_design.JedecSpec/revision :dram_design.JedecSpec/compliant])]
     (paginate rows opts))))

(defn get-jedec-spec
  "Retrieve a JedecSpec by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-jedec-spec port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-jedec-spec
  "Update a JedecSpec; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :dram_design.JedecSpec/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :standard) (conj [:db/add id :dram_design.JedecSpec/standard (get data :standard)]))
                   (cond-> (contains? data :revision) (conj [:db/add id :dram_design.JedecSpec/revision (get data :revision)]))
                   (cond-> (contains? data :compliant) (conj [:db/add id :dram_design.JedecSpec/compliant (as-bool (get data :compliant))]))
                   (conj [:db/add id :dram_design.JedecSpec/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-jedec-spec
  "Delete a JedecSpec."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/dramdevices" :op :create :entity "DramDevice"}
   {:method "GET" :path "/v1/dramdevices" :op :list :entity "DramDevice"}
   {:method "GET" :path "/v1/dramdevices/:id" :op :get :entity "DramDevice"}
   {:method "PATCH" :path "/v1/dramdevices/:id" :op :update :entity "DramDevice"}
   {:method "DELETE" :path "/v1/dramdevices/:id" :op :delete :entity "DramDevice"}
   {:method "POST" :path "/v1/cellarrays" :op :create :entity "CellArray"}
   {:method "GET" :path "/v1/cellarrays" :op :list :entity "CellArray"}
   {:method "GET" :path "/v1/cellarrays/:id" :op :get :entity "CellArray"}
   {:method "PATCH" :path "/v1/cellarrays/:id" :op :update :entity "CellArray"}
   {:method "DELETE" :path "/v1/cellarrays/:id" :op :delete :entity "CellArray"}
   {:method "POST" :path "/v1/banks" :op :create :entity "Bank"}
   {:method "GET" :path "/v1/banks" :op :list :entity "Bank"}
   {:method "GET" :path "/v1/banks/:id" :op :get :entity "Bank"}
   {:method "PATCH" :path "/v1/banks/:id" :op :update :entity "Bank"}
   {:method "DELETE" :path "/v1/banks/:id" :op :delete :entity "Bank"}
   {:method "POST" :path "/v1/timingprofiles" :op :create :entity "TimingProfile"}
   {:method "GET" :path "/v1/timingprofiles" :op :list :entity "TimingProfile"}
   {:method "GET" :path "/v1/timingprofiles/:id" :op :get :entity "TimingProfile"}
   {:method "PATCH" :path "/v1/timingprofiles/:id" :op :update :entity "TimingProfile"}
   {:method "DELETE" :path "/v1/timingprofiles/:id" :op :delete :entity "TimingProfile"}
   {:method "POST" :path "/v1/speedbins" :op :create :entity "SpeedBin"}
   {:method "GET" :path "/v1/speedbins" :op :list :entity "SpeedBin"}
   {:method "GET" :path "/v1/speedbins/:id" :op :get :entity "SpeedBin"}
   {:method "PATCH" :path "/v1/speedbins/:id" :op :update :entity "SpeedBin"}
   {:method "DELETE" :path "/v1/speedbins/:id" :op :delete :entity "SpeedBin"}
   {:method "POST" :path "/v1/jedecspecs" :op :create :entity "JedecSpec"}
   {:method "GET" :path "/v1/jedecspecs" :op :list :entity "JedecSpec"}
   {:method "GET" :path "/v1/jedecspecs/:id" :op :get :entity "JedecSpec"}
   {:method "PATCH" :path "/v1/jedecspecs/:id" :op :update :entity "JedecSpec"}
   {:method "DELETE" :path "/v1/jedecspecs/:id" :op :delete :entity "JedecSpec"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"dramdevices" {:create create-dram-device :list list-dram-devices :get get-dram-device :update update-dram-device :delete delete-dram-device}
   "cellarrays" {:create create-cell-array :list list-cell-arrays :get get-cell-array :update update-cell-array :delete delete-cell-array}
   "banks" {:create create-bank :list list-banks :get get-bank :update update-bank :delete delete-bank}
   "timingprofiles" {:create create-timing-profile :list list-timing-profiles :get get-timing-profile :update update-timing-profile :delete delete-timing-profile}
   "speedbins" {:create create-speed-bin :list list-speed-bins :get get-speed-bin :update update-speed-bin :delete delete-speed-bin}
   "jedecspecs" {:create create-jedec-spec :list list-jedec-specs :get get-jedec-spec :update update-jedec-spec :delete delete-jedec-spec}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "dram_design-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
